name: Deploy to Server

on:
  push:
    branches:
      - main
      - staging
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "${{ secrets.STAGING_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          HOST=${{ secrets.STAGE_HOST }}
        elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          HOST=${{ secrets.MAIN_HOST }}
        fi
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

    - name: Deployment from main
      if: github.ref == 'refs/heads/main'
      run: |
        rsync -avz -e 'ssh -o StrictHostKeyChecking=no' --delete-after $GITHUB_WORKSPACE ${{ secrets.USERNAME }}@${{ secrets.STAGE_HOST }}:/var/www/test/
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.STAGE_HOST }} 'su - aviusdev -c "cd /var/www/test/"'
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.STAGE_HOST }} 'chown -R aviusdev:aviusdev /var/www/test/'

    - name: Deployment from staging
      if: github.ref == 'refs/heads/staging'
      run: |
        rsync -avz -e 'ssh -o StrictHostKeyChecking=no' --delete-after $GITHUB_WORKSPACE ${{ secrets.USERNAME }}@${{ secrets.MAIN_HOST }}:/var/www/html/
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.MAIN_HOST }} 'su - aviusdev -c "cd /var/www/html/"'
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.MAIN_HOST }} 'chown -R aviusdev:aviusdev /var/www/html/'
